language: java
jdk:
  - openjdk11

# cache maven deps
cache:
  directories:
    - $HOME/.m2

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

git:
  quiet: true

script:
  - java --version
  - mvn clean install -U -B -V
